spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  security:
    user:
      name: user1
      password: 123
#security:
#  oauth2:
#    client:
#      client-id: clientId
#      client-secret: clientSecret
#      auto-approve-scopes: read
#      registered-redirect-uri: http://localhost:3000/token
#      authorized-grant-types: authorization_code
logging:
  level:
    root: debug