spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
security:
  oauth2:
    authorization:
      jwt:
        key-store: classpath:/key-for-jwt.jks
        key-password: P@ss
        key-alias: aliasname
        key-store-password: pAss
    client:
      client-id: clientId
      client-secret: clientSecret
#      auto-approve-scopes: read
#      registered-redirect-uri: http://localhost:3000/token
#      authorized-grant-types: authorization_code
logging:
  level:
    root: debug