spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
spring.mail:

  host: smtp.gmail.com
  port: 587
  username: system.97lynk@gmail.com
  password: 123456A@
  properties.mail:
    smtp.auth: true
    smtp.starttls.enable: true
#
#logging:
#  level.root: debug