
logging:
  level.org.springframework.security.web.FilterChainProxy: debug

spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
server:
  servlet:
    session:
      cookie:
        http-only: true
#      timeout: 1m